name: Release

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build and publish tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN || secrets.pypi_token }}
        run: |
          if [ -n "$PYPI_TOKEN" ]; then
            twine upload -u __token__ -p "$PYPI_TOKEN" dist/*
          elif [ -n "$TWINE_USERNAME" ] && [ -n "$TWINE_PASSWORD" ]; then
            twine upload dist/*
          else
            echo "Missing PyPI credentials (PYPI_API_TOKEN/pypi_token or PYPI_USERNAME/PYPI_PASSWORD)" >&2
            exit 1
          fi
      # GitHub Release is created in auto-tag workflow after tag is pushed
